### PR TITLE
Add size_hint for Bincoded

### PR DESCRIPTION
**Pull request by vlovich**
Also fixes issue #14

### CODE REVIEW

**Comment by zakarumych** [comment]
`size_hint` is intended to be extremely fast. It is used internally for optimizing out one `memmove`
If it can't it should return `None`.
Traversing value using `serde` is antonym for fast TBH :)

**Comment by vlovich** [comment]
Hmm... so I'm trying to allocate an I/O buffer up-front (not a Vec, not resizable) that will contain the serialized output. The serialized type has a Bincoded<T> type. How do I figure out the size of the I/O buffer to allocate?

**Comment by zakarumych** [comment]
Using [this](https://docs.rs/alkahest/0.3.0/alkahest/fn.serialized_size.html)

**Comment by zakarumych** [comment]
In general, when doing I/O you probably want to allocate buffer once and reuse it each time you send a message.
In this case you can do the following:
Allocate buffer that would probably fit a message of expected size.
Try to serialize it optimistically. If buffer is too small - grow. Either find out exact size needed or double buffer size until message fits. Or use hybrid approach.

**Comment by vlovich** [comment]
I'm using glommio so there's not really any opportunity to manually reuse buffers - it has its own pool. Nor would it make sense to hang onto them for my use-case.

**Comment by zakarumych** [comment]
It's actually the same thing. Except that lib is keeping the buffer.
Ask it for a buffer. Ask for a bigger one if message doesn't fit.

**Comment by zakarumych** [comment]
#17 should help

**Comment by vlovich** [comment]
Thanks!

**Pull request closed without merging**
